### PR TITLE
Migrate to TypeScript

### PR DESCRIPTION
**Pull request by whymarrh**
This PR migrates the project to TypeScript. We don't have declaration files, which is a bit of a bummer:

> [The rollup TypeScript] plugin currently cannot emit declaration files.

### CODE REVIEW

**Comment by whymarrh** [comment]
This was a relatively painless migration 👍

**Comment by whymarrh** [comment]
This work is based on #13, so that should be merged first.

**Comment by whymarrh** [comment]
I'm investigating the diff here of the output, it looks like tslib is required?

https://gist.github.com/whymarrh/6714a6ee05b75e2b0d2f1b0400ef8570/revisions

**Comment by whymarrh** [comment]
Updated with #20

**Comment by BboyAkers** [comment]
Hey @whymarrh  @brad-decker ! Do you all plan on merging this soon? 🙂 I'd like to work with it on my simple-dapp tutorial and get a pull request going on top of this one!

**Comment by whymarrh** [comment]
@BboyAkers thanks for the reminder!

**Comment by whymarrh** [comment]
There's a bit left to get the type definitions published in the npm package, but feel free to base work on this!

**Pull request merged**
