### PR TITLE
Fix broken Bowser import breaking package

### LINKED ISSUE #46: Missing exports warning from `yarn build`
The following warning is produced from `yarn build`:

```bash
$ yarn build
```
```
yarn run v1.22.4
$ rollup --config

src/index.ts → dist/metamask-onboarding.cjs.js, dist/metamask-onboarding.es.js...
created dist/metamask-onboarding.cjs.js, dist/metamask-onboarding.es.js in 1s

src/index.ts → dist/metamask-onboarding.bundle.js...
(!) Missing exports
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
src/index.ts
parse is not exported by node_modules/bowser/src/bowser.js
175: 
176:   static _detectBrowser () {
177:     const browserInfo = Bowser.parse(window.navigator.userAgent);
                                    ^
178:     if (browserInfo.browser.name === 'Firefox') {
179:       return 'FIREFOX';
created dist/metamask-onboarding.bundle.js in 708ms
```

And we do have a `namedExports` option defined for cjs:

https://github.com/MetaMask/metamask-onboarding/blob/c476b69af5da0420c8b614e7e586f33c50003e40/rollup.config.js#L32-L36

### PR DESCRIPTION
**Pull request by trapped**
Fixes #46 as suggested by @nickfla1.

### CODE REVIEW

**Comment by felixakiragreen** [comment]
@whymarrh any chance we could get a review on this? Currently I'm having to patch the package because of this.

**Comment by trapped** [comment]
@ryanml any chance to have this reviewed? It's been a month and a half and the npm package's current version is still unusable because of this issue

**Comment by delaneyj** [comment]
It's now June, without this the NPM version is not useable.

**Review by Gudahtt — APPROVED** [review]
LGTM! Sorry for the delay in reviewing - we'll aim to get a release of this package out within a day or so.

**Comment by alaslyalasel** [comment]
Asly

**Pull request merged**
